services:
  emqx:
    image: emqx/emqx:5.0.17
    container_name: emqx
    ports:
      - "1883:1883"   # MQTT messages
      - "18083:18083" # dashboard
    environment:
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: admin
